Zero-Percent-Angel/afterglow

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
- code/__DEFINES/combat.dm
- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/projectile.dm
Updated the hit lists so that limbs aren't just flying off left right and centre. The Body should obviously be the most hit thing as it's the biggest part of any person.
> Little combat tweaks

- code/datums/components/caltrop.dm
- code/game/machinery/obstacles_barricades.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/plasmaf13.dm
AE12 fire-rate buff
Plasma Carbine Nerf
> Small balance stuff

- code/modules/clothing/head/f13_helmets.dm
- code/modules/clothing/suits/heavy_armor.dm
- code/modules/crafting/items.dm
Refactored the messy code so you can restore any PA that has a restore type. Made it so the PA restores without it's cell and everything attached.
> PA restoration refactor!

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
Sometimes DMM doesn't show the problem that's going to happen, despite that- these are easy and quick fixes
:cl:
wH0_T00Kthejam made the following changes
Fixed a broken staircase
Added lit wall torches to brighten up the camp
fixed roofing
replaced mobs in the mutant powerplant
:cl:
> Quick map fixes

- code/modules/surgery/surgery_step.dm
> Surgery fixes!

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
- code/__DEFINES/time.dm
- code/controllers/subsystem/research.dm
- code/game/machinery/dance_machine.dm
- code/game/machinery/telecomms/computers/jammer.dm
- code/game/objects/structures/watercloset.dm
- code/modules/crafting/items.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/talker.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/research/designs/weapon_designs.dm
- modular_citadel/code/modules/client/loadout/backpack.dm
Round timer fix
Research fixes
New Radio station stuff
mob fixes
description fixes
Plushy bag added to loadout
> Radio station

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
The radio station left a bit to be desired so I went and enhanced some parts of it while changing others, gave it a new coat of paint- changed the outer walls to a duller concrete, got rid of the bookshelves and added various pre-war knicknacks to the building. Also a old rusty motorcycle in the parking lot.
:cl:
wH0_T00Kthejam made the following changes
Added some posters, food and drinks to the radio station
Improved the recording room
Added a motorcycle
:cl:
> Radio improvements continued

- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/datums/traits/negative.dm
- code/game/objects/items/stacks/medical.dm
- code/modules/language/codespeak.dm
- config/rules.txt
- Negative traits bonus points given increased on some
- First Aid checks added to some of the 'advanced' medical items 
- Key conflict fixed for tribal speak
- Rules updated
> Next Dev Iteration

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
Changing things to be better for the people and still lore fitting, plus getting rid of some STUPID BITCH DOOR that SHOULDN'T be there
:cl:
add: Bos meeting rooms and combat office
del: Stupid door
balance: removed super easy back entrance to bos  bunker
/:cl:
> BOS Bunker Changes

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
we love wiring
Little wiring mistake fixed teehee 
:cl:
fix: bos wiring, floating light, and ugly corner
/:cl:
> smol little bos fix

- code/modules/mob/living/simple_animal/hostile/retaliate/follwer.dm
NPC Companions and faction NPCs can now be configured to attack different factions when they see them.
> NPC Faction Configuration

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
- code/__DEFINES/armor.dm
- code/controllers/subsystem/npc_spawner.dm
- code/game/machinery/computer/terminal.dm
- code/game/objects/effects/landmarks.dm
- code/game/vault_door.dm
- code/modules/arousal/arousal.dm
- code/modules/jobs/job_types/ncr.dm
- code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/follwer.dm
- Town Remapped thanks to Jam! (I did some minor cleanup but all his work otherwise!)
- Secret stuff! 😄
- Legion NPC events and new legion NPC types - The legion will now invade various points of interest on the map spawning large waves of tuned up legion NPCs so be warned! These NPCs will warn you to leave the areas they are in before they open fire! Unless you're NCR they will no esc you then!
- No more stealing undies psionically
- Mob rebalancing, mobs are slightly more dangerous now!
- New NCR base.
> Fairly large changes

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
Missed some things, added more drugs and dirt to the correct areas to make it feel more grimy, also put in colour mates into faction bases (NCR.LEGION) not Brotherhood. Yet.
:cl:
wH0_T00Kthejam added the following:
Added the correct floor-tiles to missing ones.
Removed MP armband- Broken icon.
Added more Dirt.
Changed the interior of the Khan gas station slightly.
:cl:
> Fixes minor issues

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
- code/game/objects/effects/spawners/lootdrop.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/follwer.dm
- code/modules/research/designs/weapon_designs.dm
- Loot drop fixes
- Small Guard tweaks
- Research fixes
- BoS given a spare two Armour sets
> More changes

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
- code/modules/jobs/job_types/followers.dm
- Enclave get a little jail now for abductions
- Fixes to the followers descriptions
> Little server changes

- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
- code/datums/components/crafting/recipes/recipes_assemblies.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/game/objects/items/circuitboards/computer_circuitboards.dm
- code/game/objects/items/granters.dm
- code/modules/clothing/head/f13_helmets.dm
- code/modules/research/machinery/_production.dm
- code/modules/research/machinery/science_lab.dm
- code/modules/research/rdconsole.dm
- Added a way to construct RnD machines from nothing (loot table)
- Added some new crafts in to make protolathes and Circuit imprinters 
- Legion map fixes (railings)
- Couple of small map tweaks
- Enclave RnD
- RnD machines will now check for nearby consoles to connect to for tech net
-  Salvage PA hair fix?
> More updates

- _maps/map_files/Vegas Valley/Vegas_Valley_Underground.dmm
This PR simply remakes the Enclave base from mostly scratch, and touches some of the sewer around it. 
Balance wise it's mostly the same. some quality of life additions, and adds a server for their RND
:cl:
tweak: Remakes the Enclave base
/:cl:
> Remakes the Enclave base

- code/game/objects/structures/crates_lockers/closets.dm
- code/modules/fallout/obj/bosbasepicker.dm
Enclave shuttle + Closets fix (They actually grab stuff that is mapped on top of them now)
> Small fixes

- code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Alcohol number adjustments, one shouldn't be getting drunk off a sip of wine!
> Dialed in some alcohol numbers after some testing

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
- _maps/map_files/Vegas Valley/Vegas_Valley_Surface.dmm
I opened up DMM one day and saw the eyesore that was the upper Z of the powerplant. Like empty canvas, and after a Fallout 2 run, I knew what to add. Lots of night-kin and good loot to be found in this upper level as well as the bits and pieces to create your own fully functioning RND setup. Though the fight to said loot might be too easy, difficulty is subjective.
:cl:
wH0 T00Kthejam added:
A whole new dungeon.
The parts for a functioning RND
Rare loot
:cl:
> Mutant powerplant Upper level.

- _maps/map_files/Vegas Valley/Vegas_Valley_Sky.dmm
Add some mobs, took some loot away 50% more cheese. 100% personal lockers in walls.
:cl:
wH0 T00Kthejam added:
Added some mobs
Removed some Loot.
More chew-chew.
:cl:
> Tweaks the powerplant upper level.

- _maps/map_files/Tipton/Dungeons_1.dmm
- _maps/map_files/Tipton/Tipton-Sky-3.dmm
- _maps/map_files/Tipton/Tipton-Surface-2.dmm
- _maps/map_files/Tipton/Tipton-Underground-1.dmm
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
> misc fixes

- _maps/map_files/Tipton/Tipton-Surface-2.dmm
- _maps/map_files/Tipton/Tipton-Underground-1.dmm
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
> stetos plus circuit

- _maps/map_files/Tipton/Dungeons_1.dmm
- _maps/map_files/Tipton/Tipton-Sky-3.dmm
- _maps/map_files/Tipton/Tipton-Surface-2.dmm
- _maps/map_files/Tipton/Tipton-Underground-1.dmm
- code/game/objects/effects/spawners/f13lootdrop.dm
> More Fixes
